sudo: required
services:
    - docker
before_install:
    - docker pull gauravgarg9191/bwce:bwce
    - docker build -f GetSample_Dockerfile -t getsample .
script:
    - docker run -ti --name=getsample -p 80:80 -e="BW_PROFILE=Docker" -e="port=80" getsample:latest    
deploy:
    skip_cleanup: true
    - provider: elasticbeanstalk
    region: "us-east-2"
    app: "BWCE-FirstProject"
    env: "BwceFirstproject-env"
    bucket_name: "elasticbeanstalk-us-east-2-298552160667"
    bucket_path: "BWCE-FirstProject"
    on:
        branch: master
        repo: gorugarg/BWCE1
        
    access_key_id: $AWS_AccessKey
    secret_access_key:
         secure: "$AWS_SecureKey"